#!/usr/bin/env node

const fs = require("fs")
const path = require("path")

function exists(filePath) {
  return fs.existsSync(filePath)
}

function isDirectory(filePath) {
  return exists(filePath) && fs.statSync(filePath).isDirectory()
}

function mkdirp(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true })
}

const generatedHeader = "// Generated by axios-token-baseurl-error. Keep business endpoint wrappers in feature modules.\n"

function withGeneratedHeader(content) {
  return content.startsWith(generatedHeader) ? content : `${generatedHeader}${content}`
}

function includesAll(content, patterns) {
  return patterns.every((pattern) => content.includes(pattern))
}

function isManagedGeneratedApiFile(filePath, content) {
  if (content.includes("Generated by axios-token-baseurl-error")) return true

  const fileName = path.basename(filePath)

  if (/^client\.[jt]s$/u.test(fileName)) {
    return content.includes("getAccessToken")
      && content.includes("apiClient")
      && (content.includes("axios.create") || content.includes("$fetch") || content.includes("ApiFetchConfig"))
  }

  if (/^methods\.[jt]s$/u.test(fileName)) {
    return includesAll(content, ["ApiRequestOptions", "requestWithMethod", "export const api"])
  }

  if (/^helpers\.[jt]s$/u.test(fileName)) {
    return includesAll(content, ["ApiFunction", "callApi", "getApi"])
  }

  if (/^errors\.[jt]s$/u.test(fileName)) {
    return includesAll(content, ["normalizeApiError", "ApiError"])
  }

  if (/^token\.[jt]s$/u.test(fileName)) {
    return includesAll(content, ["AccessTokenProvider", "setAccessTokenProvider", "getAccessToken"])
  }

  if (/^types\.[jt]s$/u.test(fileName)) {
    return content.includes("ApiError") || content.includes("ApiFetchConfig") || content.includes("ApiMethod")
  }

  if (/^index\.[jt]s$/u.test(fileName)) {
    return includesAll(content, ["export * from './client'", "export * from './methods'", "export * from './helpers'"])
  }

  return false
}

function writeApiFile(filePath, content) {
  const nextContent = withGeneratedHeader(content)

  if (!exists(filePath)) {
    mkdirp(path.dirname(filePath))
    fs.writeFileSync(filePath, nextContent)
    console.log(`axios-token-baseurl-error: wrote ${toPosix(filePath)}`)
    return
  }

  const existingContent = fs.readFileSync(filePath, "utf8")

  if (existingContent === nextContent) {
    console.log(`axios-token-baseurl-error: kept existing ${toPosix(filePath)}`)
    return
  }

  if (isManagedGeneratedApiFile(filePath, existingContent)) {
    fs.writeFileSync(filePath, nextContent)
    console.log(`axios-token-baseurl-error: updated generated ${toPosix(filePath)}`)
    return
  }

  console.log(`axios-token-baseurl-error: kept custom ${toPosix(filePath)}`)
}

function toPosix(filePath) {
  return filePath.replace(/\\/g, "/")
}

function hasAnyFile(dirPath) {
  if (!isDirectory(dirPath)) return false
  return fs.readdirSync(dirPath).some((name) => /\.(ts|tsx|js|jsx|vue)$/u.test(name))
}

function apiFiles(dirPath) {
  if (!isDirectory(dirPath)) return []

  return fs.readdirSync(dirPath, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.(ts|tsx|js|jsx)$/u.test(entry.name))
    .map((entry) => path.join(dirPath, entry.name))
}

function hasManagedGeneratedApiFiles(dirPath) {
  return apiFiles(dirPath).some((filePath) => {
    const content = fs.readFileSync(filePath, "utf8")
    return isManagedGeneratedApiFile(filePath, content)
  })
}

function hasCustomApiTransportFile(dirPath) {
  return apiFiles(dirPath).some((filePath) => {
    const content = fs.readFileSync(filePath, "utf8")
    if (isManagedGeneratedApiFile(filePath, content)) return false

    return /axios\.create|\$fetch|apiClient|normalizeApiError|setAccessTokenProvider/u.test(content)
  })
}

function usesTypeScript() {
  return exists("tsconfig.json")
    || exists("tsconfig.app.json")
    || exists("tsconfig.node.json")
    || exists("nuxt.config.ts")
    || exists("vite.config.ts")
}

function isNuxtProject() {
  if (exists("nuxt.config.ts") || exists("nuxt.config.js") || exists("nuxt.config.mjs")) return true
  if (!exists("package.json")) return false

  try {
    const manifest = JSON.parse(fs.readFileSync("package.json", "utf8"))
    return Boolean(manifest.dependencies?.nuxt || manifest.devDependencies?.nuxt)
  } catch {
    return false
  }
}

function unique(items) {
  return [...new Set(items)]
}

function samePath(left, right) {
  return path.normalize(left) === path.normalize(right)
}

function includesPath(items, candidate) {
  return items.some((item) => samePath(item, candidate))
}

function rootPath(root, ...segments) {
  return root === "." ? path.join(...segments) : path.join(root, ...segments)
}

function sharedFeaturesLayoutRoots() {
  return ["src", "."].filter((root) => {
    return (root === "." || isDirectory(root)) &&
      (isDirectory(rootPath(root, "features")) || isDirectory(rootPath(root, "shared")))
  })
}

function sharedFeaturesLayoutRoot() {
  const roots = sharedFeaturesLayoutRoots()
  return roots.find((root) => isDirectory(rootPath(root, "shared"))) || roots[0] || ""
}

function hasSharedFeaturesBasedLayout() {
  return sharedFeaturesLayoutRoots().length > 0
}

function sharedFeaturesApiDirs() {
  return sharedFeaturesLayoutRoots().map((root) => rootPath(root, "shared", "api"))
}

function preferredApiDirs(isNuxt) {
  if (hasSharedFeaturesBasedLayout()) {
    const sharedRoot = sharedFeaturesLayoutRoot()
    return [
      rootPath(sharedRoot, "shared", "api"),
      ...sharedFeaturesApiDirs(),
    ]
  }

  if (isNuxt) {
    if (isDirectory("app")) {
      return [
        path.join("app", "utils", "api"),
        path.join("app", "lib", "api"),
        path.join("app", "composables", "api"),
        path.join("app", "api"),
      ]
    }

    if (isDirectory("src")) {
      return [
        path.join("src", "utils", "api"),
        path.join("src", "lib", "api"),
        path.join("src", "services", "api"),
        path.join("src", "api"),
      ]
    }

    return [path.join("utils", "api"), "api"]
  }

  if (isDirectory("src")) {
    return [
      path.join("src", "api"),
      path.join("src", "lib", "api"),
      path.join("src", "services", "api"),
      path.join("src", "utils", "api"),
    ]
  }

  return ["api", path.join("lib", "api"), path.join("services", "api"), path.join("utils", "api")]
}

function knownApiDirs() {
  return [
    "src/shared/api",
    "shared/api",
    "src/app/api",
    "src/lib/api",
    "src/api",
    "src/services/api",
    "src/utils/api",
    "app/utils/api",
    "app/lib/api",
    "app/composables/api",
    "app/api",
    "lib/api",
    "services/api",
    "utils/api",
    "api",
  ]
}

function misplacedGeneratedApiDirs() {
  const sharedApiDirs = sharedFeaturesApiDirs()
  return knownApiDirs().filter((candidate) => !includesPath(sharedApiDirs, candidate))
}

function chooseApiDir(isNuxt) {
  const preferred = unique(preferredApiDirs(isNuxt))
  const known = hasSharedFeaturesBasedLayout()
    ? sharedFeaturesApiDirs()
    : knownApiDirs()
  const fallbacks = known.filter((candidate) => !includesPath(preferred, candidate))
  const candidates = unique([...preferred, ...fallbacks])

  const customApiDir = candidates.find(hasCustomApiTransportFile)
  if (customApiDir) return customApiDir

  const managedApiDir = preferred.find(hasManagedGeneratedApiFiles)
  if (managedApiDir) return managedApiDir

  const existingPreferredDir = preferred.find(isDirectory)
  if (existingPreferredDir) return existingPreferredDir

  return preferred[0] || "api"
}

function removeGeneratedMisplacedApiFiles(targetDir) {
  if (!hasSharedFeaturesBasedLayout()) return

  for (const candidateDir of misplacedGeneratedApiDirs()) {
    if (samePath(candidateDir, targetDir) || !isDirectory(candidateDir)) continue

    const generatedFiles = apiFiles(candidateDir).filter((filePath) => {
      const content = fs.readFileSync(filePath, "utf8")
      return isManagedGeneratedApiFile(filePath, content)
    })

    for (const filePath of generatedFiles) {
      fs.unlinkSync(filePath)
      console.log(`axios-token-baseurl-error: removed misplaced generated ${toPosix(filePath)}`)
    }

    try {
      if (fs.readdirSync(candidateDir).length === 0) fs.rmdirSync(candidateDir)
    } catch {
      // Keep non-empty or externally managed directories intact.
    }
  }
}

const ext = usesTypeScript() ? "ts" : "js"
const isNuxt = isNuxtProject()
const apiDir = chooseApiDir(isNuxt)

const typeModule = ext === "ts"
  ? `export type ApiErrorPayload = { message?: string; code?: string; details?: unknown }

export class ApiError extends Error {
  status?: number
  code?: string
  details?: unknown

  constructor(input: { message: string; status?: number; code?: string; details?: unknown }) {
    super(input.message)
    this.status = input.status
    this.code = input.code
    this.details = input.details
  }
}
`
  : `export class ApiError extends Error {
  constructor(input) {
    super(input.message)
    this.status = input.status
    this.code = input.code
    this.details = input.details
  }
}
`

const tokenModule = ext === "ts"
  ? `export type AccessTokenProvider = () => string | null | undefined

let accessTokenProvider: AccessTokenProvider = () => {
  if (typeof window === 'undefined') return ''
  return window.localStorage.getItem('accessToken')
}

export function setAccessTokenProvider(provider: AccessTokenProvider) {
  accessTokenProvider = provider
}

export function getAccessToken() {
  return accessTokenProvider() || ''
}
`
  : `let accessTokenProvider = () => {
  if (typeof window === 'undefined') return ''
  return window.localStorage.getItem('accessToken')
}

export function setAccessTokenProvider(provider) {
  accessTokenProvider = provider
}

export function getAccessToken() {
  return accessTokenProvider() || ''
}
`

let errorsModule = ext === "ts"
  ? `import axios from 'axios'
import { ApiError, type ApiErrorPayload } from './types'

export function normalizeApiError(error: unknown) {
  if (error instanceof ApiError) return error

  if (axios.isAxiosError<ApiErrorPayload>(error)) {
    const status = error.response?.status ?? 0
    const payload = error.response?.data

    return new ApiError({
      message: payload?.message ?? error.message ?? 'Request failed.',
      status,
      code: payload?.code ?? 'UNKNOWN_ERROR',
      details: payload ?? error.message,
    })
  }

  return new ApiError({
    message: 'Request failed.',
    details: error,
  })
}
`
  : `import axios from 'axios'
import { ApiError } from './types'

export function normalizeApiError(error) {
  if (error instanceof ApiError) return error

  if (axios.isAxiosError(error)) {
    const status = error.response?.status ?? 0
    const payload = error.response?.data

    return new ApiError({
      message: payload?.message ?? error.message ?? 'Request failed.',
      status,
      code: payload?.code ?? 'UNKNOWN_ERROR',
      details: payload ?? error.message,
    })
  }

  return new ApiError({
    message: 'Request failed.',
    details: error,
  })
}
`

let clientModule = ext === "ts"
  ? `import axios, { AxiosHeaders } from 'axios'
import { getAccessToken } from './token'

function resolveApiBaseUrl() {
  const env = (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env
  return env?.VITE_API_BASE_URL || '/api'
}

export const apiClient = axios.create({
  baseURL: resolveApiBaseUrl(),
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
})

apiClient.interceptors.request.use((config) => {
  const headers = AxiosHeaders.from(config.headers)
  const accessToken = getAccessToken()

  if (accessToken) headers.set('Authorization', \`Bearer \${accessToken}\`)

  config.headers = headers
  return config
})
`
  : `import axios, { AxiosHeaders } from 'axios'
import { getAccessToken } from './token'

function resolveApiBaseUrl() {
  const env = import.meta.env || {}
  return env.VITE_API_BASE_URL || '/api'
}

export const apiClient = axios.create({
  baseURL: resolveApiBaseUrl(),
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
})

apiClient.interceptors.request.use((config) => {
  const headers = AxiosHeaders.from(config.headers)
  const accessToken = getAccessToken()

  if (accessToken) headers.set('Authorization', \`Bearer \${accessToken}\`)

  config.headers = headers
  return config
})
`

let methodsModule = ext === "ts"
  ? `import type { AxiosRequestConfig, AxiosResponse, Method } from 'axios'
import { apiClient } from './client'
import { normalizeApiError } from './errors'

export type QueryValue = string | number | boolean | null | undefined
export type QueryParams = Record<string, QueryValue | QueryValue[]>
export type HeaderValue = string | number | boolean | null | undefined
export type HeaderParams = Record<string, HeaderValue>
export type HttpMethod = Method
export type ApiRequestConfig = AxiosRequestConfig

export type ApiRequestOptions<TBody = unknown> = {
  method: HttpMethod
  url: string
  query?: QueryParams
  params?: QueryParams
  body?: TBody
  data?: TBody
  headers?: HeaderParams
  config?: ApiRequestConfig
}

function hasOwn(object: object, key: PropertyKey) {
  return Object.prototype.hasOwnProperty.call(object, key)
}

function mergeHeaders(
  configHeaders: ApiRequestConfig['headers'],
  headers?: HeaderParams,
): ApiRequestConfig['headers'] {
  const output: Record<string, string> = {
    ...((configHeaders && typeof configHeaders === 'object') ? configHeaders as Record<string, string> : {}),
  }

  for (const [name, value] of Object.entries(headers || {})) {
    if (value === null || value === undefined) {
      delete output[name]
    } else {
      output[name] = String(value)
    }
  }

  return output
}

function buildRequestConfig<TBody>(options: ApiRequestOptions<TBody>): ApiRequestConfig {
  const config = options.config || {}
  const data = hasOwn(options, 'body')
    ? options.body
    : hasOwn(options, 'data')
      ? options.data
      : config.data

  return {
    ...config,
    method: options.method,
    url: options.url,
    params: options.query || options.params || config.params,
    data,
    headers: mergeHeaders(config.headers, options.headers),
  }
}

export async function apiResponse<TResponse = unknown, TBody = unknown>(
  options: ApiRequestOptions<TBody>,
): Promise<AxiosResponse<TResponse>> {
  try {
    return await apiClient.request<TResponse>(buildRequestConfig(options))
  } catch (error) {
    throw normalizeApiError(error)
  }
}

export async function apiRequest<TResponse = unknown, TBody = unknown>(
  options: ApiRequestOptions<TBody>,
): Promise<TResponse> {
  const response = await apiResponse<TResponse, TBody>(options)
  return response.data
}

export type ApiMethod = <TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) => Promise<TResponse>

export type ApiResponseMethod = <TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) => Promise<AxiosResponse<TResponse>>

function requestWithMethod(method: HttpMethod): ApiMethod {
  return <TResponse = unknown, TBody = unknown>(
    endpoint: string,
    query?: QueryParams,
    body?: TBody,
    config?: ApiRequestConfig,
  ) => apiRequest<TResponse, TBody>({ method, url: endpoint, query, body, config })
}

function responseWithMethod(method: HttpMethod): ApiResponseMethod {
  return <TResponse = unknown, TBody = unknown>(
    endpoint: string,
    query?: QueryParams,
    body?: TBody,
    config?: ApiRequestConfig,
  ) => apiResponse<TResponse, TBody>({ method, url: endpoint, query, body, config })
}

export const api = {
  request: apiRequest,
  response: apiResponse,
  get: requestWithMethod('GET'),
  post: requestWithMethod('POST'),
  put: requestWithMethod('PUT'),
  patch: requestWithMethod('PATCH'),
  delete: requestWithMethod('DELETE'),
  getResponse: responseWithMethod('GET'),
  postResponse: responseWithMethod('POST'),
  putResponse: responseWithMethod('PUT'),
  patchResponse: responseWithMethod('PATCH'),
  deleteResponse: responseWithMethod('DELETE'),
}
`
  : `import { apiClient } from './client'
import { normalizeApiError } from './errors'

function hasOwn(object, key) {
  return Object.prototype.hasOwnProperty.call(object, key)
}

function mergeHeaders(configHeaders, headers) {
  const output = {
    ...((configHeaders && typeof configHeaders === 'object') ? configHeaders : {}),
  }

  for (const [name, value] of Object.entries(headers || {})) {
    if (value === null || value === undefined) {
      delete output[name]
    } else {
      output[name] = String(value)
    }
  }

  return output
}

function buildRequestConfig(options) {
  const config = options.config || {}
  const data = hasOwn(options, 'body')
    ? options.body
    : hasOwn(options, 'data')
      ? options.data
      : config.data

  return {
    ...config,
    method: options.method,
    url: options.url,
    params: options.query || options.params || config.params,
    data,
    headers: mergeHeaders(config.headers, options.headers),
  }
}

export async function apiResponse(options) {
  try {
    return await apiClient.request(buildRequestConfig(options))
  } catch (error) {
    throw normalizeApiError(error)
  }
}

export async function apiRequest(options) {
  const response = await apiResponse(options)
  return response.data
}

function requestWithMethod(method) {
  return (endpoint, query, body, config) => apiRequest({ method, url: endpoint, query, body, config })
}

function responseWithMethod(method) {
  return (endpoint, query, body, config) => apiResponse({ method, url: endpoint, query, body, config })
}

export const api = {
  request: apiRequest,
  response: apiResponse,
  get: requestWithMethod('GET'),
  post: requestWithMethod('POST'),
  put: requestWithMethod('PUT'),
  patch: requestWithMethod('PATCH'),
  delete: requestWithMethod('DELETE'),
  getResponse: responseWithMethod('GET'),
  postResponse: responseWithMethod('POST'),
  putResponse: responseWithMethod('PUT'),
  patchResponse: responseWithMethod('PATCH'),
  deleteResponse: responseWithMethod('DELETE'),
}
`

let helpersModule = ext === "ts"
  ? `import type { ApiRequestConfig, HttpMethod, QueryParams } from './methods'
import { api } from './methods'

export type ApiFunction<TResponse = unknown, TBody = unknown> = (
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) => Promise<TResponse>

export function callApi<TResponse = unknown, TBody = unknown>(
  method: HttpMethod,
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.request<TResponse, TBody>({
    method,
    url: endpoint,
    query,
    body,
    config,
  })
}

export function createApiFunction(method: HttpMethod) {
  return <TResponse = unknown, TBody = unknown>(
    endpoint: string,
    query?: QueryParams,
    body?: TBody,
    config?: ApiRequestConfig,
  ) => callApi<TResponse, TBody>(method, endpoint, query, body, config)
}

export function getApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.get<TResponse, TBody>(endpoint, query, body, config)
}

export function postApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.post<TResponse, TBody>(endpoint, query, body, config)
}

export function putApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.put<TResponse, TBody>(endpoint, query, body, config)
}

export function patchApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.patch<TResponse, TBody>(endpoint, query, body, config)
}

export function deleteApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.delete<TResponse, TBody>(endpoint, query, body, config)
}
`
  : `import { api } from './methods'

export function callApi(method, endpoint, query, body, config) {
  return api.request({
    method,
    url: endpoint,
    query,
    body,
    config,
  })
}

export function createApiFunction(method) {
  return (endpoint, query, body, config) => callApi(method, endpoint, query, body, config)
}

export function getApi(endpoint, query, body, config) {
  return api.get(endpoint, query, body, config)
}

export function postApi(endpoint, query, body, config) {
  return api.post(endpoint, query, body, config)
}

export function putApi(endpoint, query, body, config) {
  return api.put(endpoint, query, body, config)
}

export function patchApi(endpoint, query, body, config) {
  return api.patch(endpoint, query, body, config)
}

export function deleteApi(endpoint, query, body, config) {
  return api.delete(endpoint, query, body, config)
}
`

const nuxtFetchErrorsModule = ext === "ts"
  ? `import { ApiError, type ApiErrorPayload } from './types'

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

function getPayloadMessage(payload: unknown, fallback: string) {
  return isObject(payload) && typeof payload.message === 'string' ? payload.message : fallback
}

function getPayloadCode(payload: unknown) {
  return isObject(payload) && typeof payload.code === 'string' ? payload.code : 'UNKNOWN_ERROR'
}

export function normalizeApiError(error: unknown) {
  if (error instanceof ApiError) return error

  if (isObject(error)) {
    const response = isObject(error.response) ? error.response : undefined
    const payload = (response?._data ?? response?.data ?? error.data) as ApiErrorPayload | undefined
    const statusValue = response?.status ?? error.statusCode ?? error.status
    const status = typeof statusValue === 'number' ? statusValue : Number(statusValue || 0)
    const fallbackMessage = typeof error.message === 'string' ? error.message : 'Request failed.'

    return new ApiError({
      message: getPayloadMessage(payload, fallbackMessage),
      status,
      code: getPayloadCode(payload),
      details: payload ?? error,
    })
  }

  return new ApiError({
    message: 'Request failed.',
    details: error,
  })
}
`
  : `import { ApiError } from './types'

function isObject(value) {
  return typeof value === 'object' && value !== null
}

function getPayloadMessage(payload, fallback) {
  return isObject(payload) && typeof payload.message === 'string' ? payload.message : fallback
}

function getPayloadCode(payload) {
  return isObject(payload) && typeof payload.code === 'string' ? payload.code : 'UNKNOWN_ERROR'
}

export function normalizeApiError(error) {
  if (error instanceof ApiError) return error

  if (isObject(error)) {
    const response = isObject(error.response) ? error.response : undefined
    const payload = response?._data ?? response?.data ?? error.data
    const statusValue = response?.status ?? error.statusCode ?? error.status
    const status = typeof statusValue === 'number' ? statusValue : Number(statusValue || 0)
    const fallbackMessage = typeof error.message === 'string' ? error.message : 'Request failed.'

    return new ApiError({
      message: getPayloadMessage(payload, fallbackMessage),
      status,
      code: getPayloadCode(payload),
      details: payload ?? error,
    })
  }

  return new ApiError({
    message: 'Request failed.',
    details: error,
  })
}
`

const nuxtFetchClientModule = ext === "ts"
  ? `import { $fetch, useRuntimeConfig } from '#imports'
import { getAccessToken } from './token'

export type ApiFetchConfig = {
  headers?: HeadersInit
  signal?: AbortSignal
  timeout?: number
  credentials?: RequestCredentials
  retry?: number | false
  baseURL?: string
  [key: string]: unknown
}

export type ApiFetchResponse<TResponse = unknown> = {
  _data?: TResponse
  status: number
  statusText?: string
  headers: Headers
}

type NuxtFetchOptions = NonNullable<Parameters<typeof $fetch>[1]>

function getConfigValue(config: Record<string, unknown>, keys: string[]) {
  for (const key of keys) {
    const value = config[key]
    if (typeof value === 'string' && value.length > 0) return value
  }

  return ''
}

export function resolveApiBaseUrl() {
  const runtimeConfig = useRuntimeConfig()
  const publicConfig = runtimeConfig.public as Record<string, unknown>

  return getConfigValue(publicConfig, [
    'apiBase',
    'apiBaseUrl',
    'apiBaseURL',
    'apiUrl',
    'apiURL',
  ]) || '/api'
}

function mergeHeaders(input?: HeadersInit) {
  const headers = new Headers(input)
  const accessToken = getAccessToken()

  if (!headers.has('Accept')) headers.set('Accept', 'application/json')
  if (accessToken) headers.set('Authorization', \`Bearer \${accessToken}\`)

  return headers
}

function withApiDefaults(config: ApiFetchConfig = {}): NuxtFetchOptions {
  const baseURL = typeof config.baseURL === 'string' ? config.baseURL : resolveApiBaseUrl()

  return {
    ...config,
    baseURL,
    headers: mergeHeaders(config.headers),
  } as NuxtFetchOptions
}

export function apiClient<TResponse = unknown>(
  endpoint: string,
  config: ApiFetchConfig = {},
): Promise<TResponse> {
  return $fetch<TResponse>(endpoint, withApiDefaults(config))
}

export function apiClientRaw<TResponse = unknown>(
  endpoint: string,
  config: ApiFetchConfig = {},
): Promise<ApiFetchResponse<TResponse>> {
  return $fetch.raw<TResponse>(endpoint, withApiDefaults(config)) as Promise<ApiFetchResponse<TResponse>>
}
`
  : `import { $fetch, useRuntimeConfig } from '#imports'
import { getAccessToken } from './token'

function getConfigValue(config, keys) {
  for (const key of keys) {
    const value = config[key]
    if (typeof value === 'string' && value.length > 0) return value
  }

  return ''
}

export function resolveApiBaseUrl() {
  const runtimeConfig = useRuntimeConfig()
  const publicConfig = runtimeConfig.public || {}

  return getConfigValue(publicConfig, [
    'apiBase',
    'apiBaseUrl',
    'apiBaseURL',
    'apiUrl',
    'apiURL',
  ]) || '/api'
}

function mergeHeaders(input) {
  const headers = new Headers(input)
  const accessToken = getAccessToken()

  if (!headers.has('Accept')) headers.set('Accept', 'application/json')
  if (accessToken) headers.set('Authorization', \`Bearer \${accessToken}\`)

  return headers
}

function withApiDefaults(config = {}) {
  const baseURL = typeof config.baseURL === 'string' ? config.baseURL : resolveApiBaseUrl()

  return {
    ...config,
    baseURL,
    headers: mergeHeaders(config.headers),
  }
}

export function apiClient(endpoint, config = {}) {
  return $fetch(endpoint, withApiDefaults(config))
}

export function apiClientRaw(endpoint, config = {}) {
  return $fetch.raw(endpoint, withApiDefaults(config))
}
`

const nuxtFetchMethodsModule = ext === "ts"
  ? `import { apiClient, apiClientRaw, type ApiFetchConfig, type ApiFetchResponse } from './client'
import { normalizeApiError } from './errors'

export type QueryValue = string | number | boolean | null | undefined
export type QueryParams = Record<string, QueryValue | QueryValue[]>
export type HeaderValue = string | number | boolean | null | undefined
export type HeaderParams = Record<string, HeaderValue>
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export type ApiRequestConfig = ApiFetchConfig

export type ApiRequestOptions<TBody = unknown> = {
  method: HttpMethod
  url: string
  query?: QueryParams
  params?: QueryParams
  body?: TBody
  data?: TBody
  headers?: HeaderParams | HeadersInit
  config?: ApiRequestConfig
}

function hasOwn(object: object, key: PropertyKey) {
  return Object.prototype.hasOwnProperty.call(object, key)
}

function applyHeader(headers: Headers, name: string, value: HeaderValue) {
  if (value === null || value === undefined) {
    headers.delete(name)
  } else {
    headers.set(name, String(value))
  }
}

function mergeHeaders(
  configHeaders?: HeadersInit,
  headers?: HeaderParams | HeadersInit,
): Headers {
  const output = new Headers(configHeaders)

  if (!headers) return output

  if (headers instanceof Headers || Array.isArray(headers)) {
    new Headers(headers).forEach((value, name) => output.set(name, value))
    return output
  }

  for (const [name, value] of Object.entries(headers as HeaderParams)) {
    applyHeader(output, name, value)
  }

  return output
}

function buildRequestConfig<TBody>(options: ApiRequestOptions<TBody>): ApiRequestConfig {
  const config = options.config || {}
  const data = hasOwn(options, 'body')
    ? options.body
    : hasOwn(options, 'data')
      ? options.data
      : (config.body ?? config.data) as TBody | undefined
  const query = options.query || options.params || (config.query ?? config.params) as QueryParams | undefined

  return {
    ...config,
    method: options.method,
    query,
    body: data,
    headers: mergeHeaders(config.headers, options.headers),
  }
}

export async function apiResponse<TResponse = unknown, TBody = unknown>(
  options: ApiRequestOptions<TBody>,
): Promise<ApiFetchResponse<TResponse>> {
  try {
    return await apiClientRaw<TResponse>(options.url, buildRequestConfig(options))
  } catch (error) {
    throw normalizeApiError(error)
  }
}

export async function apiRequest<TResponse = unknown, TBody = unknown>(
  options: ApiRequestOptions<TBody>,
): Promise<TResponse> {
  try {
    return await apiClient<TResponse>(options.url, buildRequestConfig(options))
  } catch (error) {
    throw normalizeApiError(error)
  }
}

export type ApiMethod = <TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) => Promise<TResponse>

export type ApiResponseMethod = <TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) => Promise<ApiFetchResponse<TResponse>>

function requestWithMethod(method: HttpMethod): ApiMethod {
  return <TResponse = unknown, TBody = unknown>(
    endpoint: string,
    query?: QueryParams,
    body?: TBody,
    config?: ApiRequestConfig,
  ) => apiRequest<TResponse, TBody>({ method, url: endpoint, query, body, config })
}

function responseWithMethod(method: HttpMethod): ApiResponseMethod {
  return <TResponse = unknown, TBody = unknown>(
    endpoint: string,
    query?: QueryParams,
    body?: TBody,
    config?: ApiRequestConfig,
  ) => apiResponse<TResponse, TBody>({ method, url: endpoint, query, body, config })
}

export const api = {
  request: apiRequest,
  response: apiResponse,
  get: requestWithMethod('GET'),
  post: requestWithMethod('POST'),
  put: requestWithMethod('PUT'),
  patch: requestWithMethod('PATCH'),
  delete: requestWithMethod('DELETE'),
  getResponse: responseWithMethod('GET'),
  postResponse: responseWithMethod('POST'),
  putResponse: responseWithMethod('PUT'),
  patchResponse: responseWithMethod('PATCH'),
  deleteResponse: responseWithMethod('DELETE'),
}
`
  : `import { apiClient, apiClientRaw } from './client'
import { normalizeApiError } from './errors'

function hasOwn(object, key) {
  return Object.prototype.hasOwnProperty.call(object, key)
}

function applyHeader(headers, name, value) {
  if (value === null || value === undefined) {
    headers.delete(name)
  } else {
    headers.set(name, String(value))
  }
}

function mergeHeaders(configHeaders, headers) {
  const output = new Headers(configHeaders)

  if (!headers) return output

  if (headers instanceof Headers || Array.isArray(headers)) {
    new Headers(headers).forEach((value, name) => output.set(name, value))
    return output
  }

  for (const [name, value] of Object.entries(headers)) {
    applyHeader(output, name, value)
  }

  return output
}

function buildRequestConfig(options) {
  const config = options.config || {}
  const data = hasOwn(options, 'body')
    ? options.body
    : hasOwn(options, 'data')
      ? options.data
      : config.body ?? config.data
  const query = options.query || options.params || config.query || config.params

  return {
    ...config,
    method: options.method,
    query,
    body: data,
    headers: mergeHeaders(config.headers, options.headers),
  }
}

export async function apiResponse(options) {
  try {
    return await apiClientRaw(options.url, buildRequestConfig(options))
  } catch (error) {
    throw normalizeApiError(error)
  }
}

export async function apiRequest(options) {
  try {
    return await apiClient(options.url, buildRequestConfig(options))
  } catch (error) {
    throw normalizeApiError(error)
  }
}

function requestWithMethod(method) {
  return (endpoint, query, body, config) => apiRequest({ method, url: endpoint, query, body, config })
}

function responseWithMethod(method) {
  return (endpoint, query, body, config) => apiResponse({ method, url: endpoint, query, body, config })
}

export const api = {
  request: apiRequest,
  response: apiResponse,
  get: requestWithMethod('GET'),
  post: requestWithMethod('POST'),
  put: requestWithMethod('PUT'),
  patch: requestWithMethod('PATCH'),
  delete: requestWithMethod('DELETE'),
  getResponse: responseWithMethod('GET'),
  postResponse: responseWithMethod('POST'),
  putResponse: responseWithMethod('PUT'),
  patchResponse: responseWithMethod('PATCH'),
  deleteResponse: responseWithMethod('DELETE'),
}
`

const nuxtFetchHelpersModule = ext === "ts"
  ? `import type { ApiRequestConfig, HttpMethod, QueryParams } from './methods'
import { api } from './methods'

export type ApiFunction<TResponse = unknown, TBody = unknown> = (
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) => Promise<TResponse>

export function callApi<TResponse = unknown, TBody = unknown>(
  method: HttpMethod,
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.request<TResponse, TBody>({
    method,
    url: endpoint,
    query,
    body,
    config,
  })
}

export function createApiFunction(method: HttpMethod) {
  return <TResponse = unknown, TBody = unknown>(
    endpoint: string,
    query?: QueryParams,
    body?: TBody,
    config?: ApiRequestConfig,
  ) => callApi<TResponse, TBody>(method, endpoint, query, body, config)
}

export function getApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.get<TResponse, TBody>(endpoint, query, body, config)
}

export function postApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.post<TResponse, TBody>(endpoint, query, body, config)
}

export function putApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.put<TResponse, TBody>(endpoint, query, body, config)
}

export function patchApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.patch<TResponse, TBody>(endpoint, query, body, config)
}

export function deleteApi<TResponse = unknown, TBody = unknown>(
  endpoint: string,
  query?: QueryParams,
  body?: TBody,
  config?: ApiRequestConfig,
) {
  return api.delete<TResponse, TBody>(endpoint, query, body, config)
}
`
  : helpersModule

if (isNuxt) {
  errorsModule = nuxtFetchErrorsModule
  clientModule = nuxtFetchClientModule
  methodsModule = nuxtFetchMethodsModule
  helpersModule = nuxtFetchHelpersModule
}

const indexModule = `export * from './client'
export * from './token'
export * from './errors'
export * from './types'
export * from './methods'
export * from './helpers'
`

writeApiFile(path.join(apiDir, `types.${ext}`), typeModule)
writeApiFile(path.join(apiDir, `token.${ext}`), tokenModule)
writeApiFile(path.join(apiDir, `errors.${ext}`), errorsModule)
writeApiFile(path.join(apiDir, `client.${ext}`), clientModule)
writeApiFile(path.join(apiDir, `methods.${ext}`), methodsModule)
writeApiFile(path.join(apiDir, `helpers.${ext}`), helpersModule)
writeApiFile(path.join(apiDir, `index.${ext}`), indexModule)
removeGeneratedMisplacedApiFiles(apiDir)

console.log(`axios-token-baseurl-error: API client location ${toPosix(apiDir)}`)
